language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t mclovis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mclovis/docker-react npm run test -- --coverage

