version: "3.8"
services:
  react-web:
    image: "mclovis/course1"
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes:
    - /app/node_modules
    - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
#  react-test:
#    image: "mclovis/course1"
#    volumes:
#      - /app/node_modules
#      - .:/app
#    command: ["npm","run","test"]
